plugins {
    id 'com.android.application' version '8.7.3'
}
android {
    namespace 'com.supercubegame.pockettodo'
    compileSdk 35
    buildToolsVersion '35.0.0'
    defaultConfig {
        applicationId 'com.supercubegame.pockettodo'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
